Repository magicbell-io/docs, pull requests merged in 2022-06, with the labels that each got.

#113 Update Categories screenshot
  public/uploads/categories_preferences.png
Labels: bug, documentation

#116 Replace YT embeds with Wistia
  docs/changelog.mdx
  docs/email/ping.mdx
Labels: bug, documentation

#117 Update Docs screenshots
  docs/categories.mdx
  docs/channels.mdx
  docs/compose.mdx
  docs/email-layouts.mdx
  docs/log.mdx
  docs/templates.mdx
  docs/turn-on-hmac-authentication.mdx
  public/uploads/ComposeButton.png
  public/uploads/ConfigureSmartChannels.png
  public/uploads/HMAC.png
  public/uploads/Preferences.png
  public/uploads/categories_preferences.png
  public/uploads/email-layout.png
  public/uploads/logScreenshot.png
  public/uploads/templates.png
Labels: bug, documentation

#118 Fix broken URL to Mila's blog post
  docs/changelog.mdx
Labels: bug, documentation

#120 Line edits for GraphQL overview
  docs/graphql-api/overview.mdx
Labels: bug, documentation

#121 Add instructions for securely sending credentials
  docs/email/mailgun.mdx
  docs/email/postmark.mdx
  docs/email/sendgrid.mdx
  docs/slack/custom-apps.mdx
  public/uploads/magicbell-support.key
Labels: documentation, enhancement

#122 Fix broken link
  docs/changelog.mdx
  docs/react/changing-default-notification-component.mdx
Labels: bug, documentation

#123 Remove reference to MS teams
  docs/channels.mdx
Labels: bug, documentation

#124 Adds configuration integration instructions
  docs/channels.mdx
  docs/email.mdx
  docs/email/3rd-party-email-providers.mdx
  docs/email/mailgun.mdx
  docs/email/ping.mdx
  docs/email/postmark.mdx
  docs/email/sendgrid.mdx
  docs/log.mdx
  docs/mobile-push.mdx
  docs/mobile-push/ios.mdx
  docs/sms/twilio.mdx
  public/uploads/email_mailgun.gif
  public/uploads/email_ping.gif
  public/uploads/email_postmark.gif
  public/uploads/email_sendgrid.gif
  public/uploads/mobile-push_apns.gif
  public/uploads/sms_twilio.gif
  redirects.json
  sitemap.json
Labels: documentation, enhancement

#119 Document additional update-user endpoints
  docs/rest-api/reference/openapi.json
Labels: documentation, enhancement

#125 Document Projects API
  docs/rest-api/reference/openapi.json
  lib/codeSnippet.tsx
Labels: Ready for review

#127 June 13, 2022 Changelog
  docs/changelog.mdx
Labels: documentation, changelog

#128 Update footer links for playground & community
  footer.json
Labels: bug, documentation

#130 Docs repo enhancements
  README.md
  pull_request_template.md
Labels: bug

#131 Projects API (JWT token) is enterprise feature
  docs/changelog.mdx
  docs/rest-api/reference/openapi.json
Labels: bug, documentation, changelog

#132 Find and replace assets hosted in Intercom
  docs/changelog.mdx
  public/uploads/notification_preferences_beta.png
Labels: bug, documentation

#133 fix: handle search results that don't have a content prop
  src/components/layout/SearchHit.tsx
Labels: Ready for review

#135 Update FCM mobile push configuration docs
  docs/mobile-push/android.mdx
  docs/mobile-push/ios.mdx
  public/uploads/fcm_server_key.png
  public/uploads/mobile-push_fcm.gif
  public/uploads/registering-apple-key.png
  sitemap.json
Labels: bug, documentation

#137 Remove mention of delay for deleting users
  docs/rest-api/reference/openapi.json
Labels: documentation, enhancement

#140 Fix "broken" links to GraphQL API
  docs/changelog.mdx
  docs/graphql-api/overview.mdx
Labels: bug, documentation

#141 Create Notification endpoint now accepts user attributes
  docs/rest-api/reference/openapi.json
Labels: documentation, enhancement

#139 Add Amazon SES provider docs
  docs/email.mdx
  docs/email/amazon-ses.mdx
  public/uploads/email_amazon-ses.gif
  sitemap.json
Labels: documentation, enhancement

#138 Add Web Push docs
  docs/web-push.mdx
  docs/web-push/safari.mdx
  public/uploads/web-push_safari-apns.gif
  sitemap.json
Labels: documentation, enhancement

#143 Comma missing after custom_attributes in the payload dictionary
  docs/email/sendgrid.mdx
Labels: bug, documentation

#144 Jun 27, 2022 Changelog
  docs/changelog.mdx
Labels: documentation, changelog

#145 SES does not currently support overrides
  docs/email/amazon-ses.mdx
Labels: bug, documentation

#146 Add recipient hash to changelog
  docs/changelog.mdx
Labels: bug, documentation, changelog
