Repository magicbell-io/docs, pull requests merged in 2022-07, with the labels that each got.

#149 Fix the broken link in the docs
  docs/changelog.mdx
Labels: bug, documentation, changelog

#151 Add a section to explain how sending notifications to subscribers work
  docs/topics.mdx
Labels: Ready for review

#153 Add the descriptions to the Subscription related input types
  docs/graphql-api/reference/schema.graphql
Labels: Ready for review

#156 Swap link to blog for product page
  docs/web-push.mdx
Labels: bug, documentation

#158 Update topic subscriptions
  docs/graphql-api/reference/schema.graphql
  docs/rest-api/reference/openapi.json
Labels: Ready for review

#159 Rename Templates subheading in sitemap nav
  sitemap.json
Labels: bug, documentation

#157 chore: point to unpkg instead of assets.magicbell.io
  docs/adding-magicbell-to-your-product.mdx
  docs/angular.mdx
  docs/browser/changing-default-font.mdx
  docs/browser/changing-default-images.mdx
  docs/browser/new-notification-hook.mdx
  docs/react/localization-internationalization.mdx
  docs/react/theme-customization.mdx
  docs/vue/adding-magicbell-to-your-nuxt-application.mdx
Labels: enhancement

#162 Note that we don't currently support Mailgun EU tenant
  docs/email/mailgun.mdx
Labels: bug, documentation

#163 Document that we call SendGrid v3 API
  docs/email/sendgrid.mdx
Labels: bug, documentation

#164 Document logs delay
  docs/log.mdx
Labels: bug, documentation
